package org.numpol.podotaro.taro.domain

import org.numpol.podotaro.taro.presentation.TarotCard

fun getCardDetailsEnglish(card: TarotCard): List<String> {
    return when (card.description) {
        "The Fool" -> listOf(
            "New beginnings: Embracing the start of a journey with optimism.",
            "Innocence: Approaching life with a fresh, unburdened perspective.",
            "Spontaneity: Welcoming adventure and unexpected opportunities.",
            "Freedom: Letting go of conventions and taking a leap of faith.",
            "Optimism: Trusting in the promise of a bright future.",
            "Potential: Recognizing endless possibilities in the unknown.",
            "Naivety: A gentle reminder to balance risk with awareness.",
            "Adventure: Venturing into uncharted territory with enthusiasm.",
            "Creativity: Using imaginative insights to forge a new path.",
            "Curiosity: Maintaining a childlike wonder about life.",
            "Trust: Believing that the universe supports your journey.",
            "Liberation: Breaking free from past limitations.",
            "Renewal: Starting over with energy and hope.",
            "Exploration: Discovering new facets of yourself along the way.",
            "Risk: Accepting uncertainty as part of the growth process."
        )
        "The Magician" -> listOf(
            "Manifestation: Turning ideas into reality with focused intent.",
            "Resourcefulness: Using available tools and talents to overcome challenges.",
            "Willpower: Harnessing inner strength to effect change.",
            "Action: Taking decisive steps towards your goals.",
            "Creativity: Blending inspiration with skill to innovate.",
            "Focus: Concentrating energy to produce tangible outcomes.",
            "Confidence: Trusting in your ability to shape your destiny.",
            "Mastery: Refining your skills through dedicated practice.",
            "Inspiration: Drawing on the universe’s energy to fuel ambitions.",
            "Initiative: Seizing opportunities with proactive determination.",
            "Communication: Expressing ideas clearly to manifest vision.",
            "Transformation: Converting potential into reality.",
            "Empowerment: Realizing and using your inner power.",
            "Leadership: Guiding others by example and conviction.",
            "Determination: Persisting until your dreams come to fruition."
        )
        "The High Priestess" -> listOf(
            "Intuition: Trusting your inner voice and subconscious signals.",
            "Mystery: Embracing the unknown as a source of hidden wisdom.",
            "Wisdom: Seeking deeper knowledge beyond the obvious.",
            "Secrets: Recognizing that some truths are revealed gradually.",
            "Spirituality: Connecting with your inner self and higher consciousness.",
            "Perception: Understanding subtle cues in your environment.",
            "Calm: Finding peace in quiet reflection.",
            "Insight: Delving beneath the surface for true understanding.",
            "Balance: Navigating between light and shadow within yourself.",
            "Reflection: Taking time to contemplate life’s mysteries.",
            "Depth: Exploring the layers of your inner world.",
            "Introspection: Analyzing feelings and thoughts to gain clarity.",
            "Mysticism: Embracing the esoteric aspects of existence.",
            "Sensitivity: Being open to the nuances of emotion and spirit.",
            "Patience: Allowing answers to surface in their own time."
        )
        "The Empress" -> listOf(
            "Abundance: Celebrating fertility and the rewards of nurturing.",
            "Nurturing: Providing care and warmth to yourself and others.",
            "Creativity: Inspiring artistic expression and beauty.",
            "Sensuality: Enjoying life’s pleasures and natural beauty.",
            "Fertility: Symbolizing growth, creation, and new beginnings.",
            "Comfort: Creating an environment of love and support.",
            "Nature: Connecting with the natural world for healing.",
            "Prosperity: Embracing a life rich with abundance.",
            "Harmony: Balancing relationships and personal needs.",
            "Beauty: Appreciating and creating beauty in all forms.",
            "Compassion: Offering kindness and empathy generously.",
            "Growth: Fostering personal development and transformation.",
            "Nourishment: Feeding both body and soul.",
            "Feminine Energy: Celebrating intuitive and creative power.",
            "Security: Building a safe, loving foundation for the future."
        )
        "The Emperor" -> listOf(
            "Authority: Embracing leadership and clear structure in your life.",
            "Control: Taking charge of your circumstances with confidence.",
            "Stability: Building a solid foundation for lasting success.",
            "Discipline: Maintaining order through self-control and routine.",
            "Responsibility: Meeting obligations with maturity and care.",
            "Structure: Creating systems that bring clarity and direction.",
            "Power: Harnessing your inner strength to direct outcomes.",
            "Confidence: Standing firm in your decisions and beliefs.",
            "Logic: Approaching challenges with clear, rational thought.",
            "Protection: Safeguarding what is important to you.",
            "Determination: Persisting steadily in the face of obstacles.",
            "Order: Finding peace in an organized environment.",
            "Boundaries: Recognizing limits and enforcing them wisely.",
            "Tradition: Valuing time-tested methods and practices.",
            "Legacy: Building an enduring impact through wise leadership."
        )
        "The Hierophant" -> listOf(
            "Tradition: Embracing established customs and cultural wisdom.",
            "Spiritual Guidance: Seeking counsel from trusted sources.",
            "Conformity: Recognizing the value in following time‑honored practices.",
            "Faith: Drawing strength from your beliefs and values.",
            "Education: Learning through conventional systems and mentors.",
            "Morality: Upholding ethical standards in your decisions.",
            "Community: Valuing shared wisdom and collective experience.",
            "Ceremony: Participating in rituals that honor tradition.",
            "Conservatism: Respecting the wisdom of the past.",
            "Discipline: Following structured paths to growth and understanding.",
            "Spiritual Connection: Deepening your bond with the divine.",
            "Guidance: Allowing experienced voices to illuminate your path.",
            "Order: Finding comfort in established patterns.",
            "Ritual: Celebrating the sacred through practiced tradition.",
            "Belonging: Finding your place within a larger community."
        )
        "The Lovers" -> listOf(
            "Union: Celebrating deep connections and meaningful partnerships.",
            "Harmony: Balancing differences to create unity.",
            "Attraction: Feeling a magnetic pull toward another soul.",
            "Love: Embracing romance and emotional intimacy.",
            "Choice: Facing important decisions in relationships.",
            "Alignment: Finding common ground in values and desires.",
            "Intimacy: Sharing a deep, vulnerable connection.",
            "Commitment: Building lasting bonds based on trust.",
            "Passion: Experiencing powerful emotional and physical attraction.",
            "Connection: Recognizing a soul‑level bond with another.",
            "Balance: Harmonizing diverse aspects of love and life.",
            "Communication: Speaking honestly to nurture relationships.",
            "Vulnerability: Allowing yourself to be seen and understood.",
            "Partnership: Working together toward mutual growth.",
            "Union of Opposites: Merging complementary energies into one."
        )
        "The Chariot" -> listOf(
            "Determination: Charging ahead with unwavering focus.",
            "Victory: Overcoming challenges through sheer willpower.",
            "Control: Harnessing conflicting forces to move forward.",
            "Momentum: Building energy and purpose through action.",
            "Discipline: Staying on course amid distractions.",
            "Ambition: Directing energy toward a clear goal.",
            "Confidence: Believing in your ability to triumph.",
            "Balance: Merging opposing influences for a unified drive.",
            "Travel: Embarking on a journey, literal or metaphorical.",
            "Willpower: Demonstrating strength in the face of adversity.",
            "Triumph: Celebrating success after hard‑fought battles.",
            "Focus: Keeping your eyes on the prize.",
            "Courage: Facing obstacles with bravery and resolve.",
            "Resilience: Persisting despite setbacks or challenges.",
            "Direction: Steering your life with purpose and clarity."
        )
        "Strength" -> listOf(
            "Courage: Tapping into inner bravery to face life’s trials.",
            "Compassion: Using kindness and understanding to overcome difficulties.",
            "Determination: Persisting with quiet resolve despite obstacles.",
            "Patience: Enduring challenges with grace and calm.",
            "Resilience: Bouncing back from adversity with inner strength.",
            "Fortitude: Drawing on deep reserves of emotional power.",
            "Self‑Control: Mastering impulses through gentle strength.",
            "Empathy: Channeling compassion as a source of true power.",
            "Inner Strength: Recognizing the quiet force within you.",
            "Tenacity: Holding firm in your beliefs during tough times.",
            "Grace: Navigating challenges with dignity and poise.",
            "Passion: Harnessing intense emotion to fuel perseverance.",
            "Balance: Harmonizing assertiveness with gentleness.",
            "Perseverance: Continuing forward despite setbacks.",
            "Confidence: Trusting in your ability to endure and succeed."
        )
        "The Hermit" -> listOf(
            "Introspection: Seeking wisdom through solitary reflection.",
            "Contemplation: Taking time to ponder life’s deeper questions.",
            "Wisdom: Drawing insight from personal experience.",
            "Retreat: Stepping back from the world to find inner clarity.",
            "Solitude: Embracing alone time to understand your true self.",
            "Guidance: Listening to your inner voice for direction.",
            "Meditation: Finding calm and clarity in quiet moments.",
            "Reflection: Learning from your past to shape your future.",
            "Search for Truth: Delving deep to uncover hidden insights.",
            "Isolation: Recognizing the value in stepping away from noise.",
            "Enlightenment: Experiencing growth through inner discovery.",
            "Inner Journey: Exploring your own spiritual landscape.",
            "Discernment: Trusting the insights that arise in silence.",
            "Self‑Reliance: Learning to depend on your inner resources.",
            "Contemplative Solitude: Finding strength in quiet reflection."
        )
        "Wheel of Fortune" -> listOf(
            "Cycles: Recognizing the constant ebb and flow of life.",
            "Destiny: Accepting that fate plays a role in your journey.",
            "Change: Embracing the unpredictable twists of fortune.",
            "Karma: Understanding that every action has its consequence.",
            "Opportunity: Seizing moments as they arise unexpectedly.",
            "Chance: Acknowledging that luck can shift at any moment.",
            "Fate: Realizing that some aspects of life are beyond control.",
            "Turn of Events: Observing how circumstances can reverse suddenly.",
            "Flux: Adapting to change with flexibility and grace.",
            "Mystery: Accepting the unknown elements in your path.",
            "Fortune: Welcoming both luck and misfortune as part of life.",
            "Cycle Completion: Noticing the end of one phase and the start of another.",
            "Momentum: Using change to propel you forward.",
            "Unexpected Turns: Being open to surprising opportunities.",
            "Perpetuity: Understanding that life’s cycles are eternal."
        )
        "Justice" -> listOf(
            "Fairness: Striving for balance and equitable outcomes.",
            "Truth: Confronting reality with honesty and clarity.",
            "Accountability: Recognizing that actions lead to consequences.",
            "Integrity: Upholding moral principles in every decision.",
            "Law: Respecting rules and the structure they provide.",
            "Balance: Weighing all sides of an issue before deciding.",
            "Responsibility: Owning your actions and their impacts.",
            "Clarity: Seeking transparency in complex situations.",
            "Equity: Ensuring that all parties are treated justly.",
            "Reason: Relying on logic to resolve disputes.",
            "Judgment: Evaluating circumstances with fairness.",
            "Objectivity: Removing bias to see the truth clearly.",
            "Reconciliation: Working to restore balance after conflict.",
            "Decision‑Making: Choosing with a clear mind and open heart.",
            "Karma: Recognizing that fairness will ultimately return."
        )
        "The Hanged Man" -> listOf(
            "Surrender: Letting go of control to gain fresh perspective.",
            "Pause: Recognizing the value in taking a deliberate break.",
            "Sacrifice: Understanding that letting go can lead to growth.",
            "Perspective: Viewing challenges from a different angle.",
            "Letting Go: Releasing outdated patterns and attachments.",
            "Acceptance: Embracing change even when it feels uncertain.",
            "Patience: Trusting that time will reveal new insights.",
            "Insight: Finding wisdom in moments of suspension.",
            "Reversal: Recognizing that a shift in view can transform understanding.",
            "Contemplation: Using stillness to understand complex issues.",
            "Inversion: Discovering strength in vulnerability and surrender.",
            "Transition: Accepting that pause is often a precursor to progress.",
            "Reflection: Learning from the silence between actions.",
            "Resignation: Acknowledging when to step back and reassess.",
            "Renewal: Embracing a temporary halt as a path to transformation."
        )
        "Death" -> listOf(
            "Transformation: Embracing the end of one phase to welcome another.",
            "Release: Letting go of the old to make room for new growth.",
            "Transition: Recognizing that endings pave the way for fresh starts.",
            "Rebirth: Understanding that every ending seeds a new beginning.",
            "Closure: Accepting the natural conclusion of situations.",
            "Cleansing: Purging what no longer serves you to evolve.",
            "Letting Go: Freeing yourself from outdated attachments.",
            "Metamorphosis: Embracing profound change as a pathway to growth.",
            "Acceptance: Coming to terms with life’s inevitable cycles.",
            "Evolution: Recognizing that transformation is essential for progress.",
            "Reinvention: Redefining yourself after significant change.",
            "Transition: Moving forward with lessons learned from the past.",
            "Resilience: Rising stronger after letting go of the old.",
            "New Horizons: Opening yourself to the promise of a renewed future.",
            "Renewal: Seeing endings as opportunities for a fresh start."
        )
        "Temperance" -> listOf(
            "Balance: Integrating opposing forces to create harmony.",
            "Moderation: Avoiding extremes in thought and behavior.",
            "Purpose: Blending different aspects of your life into unity.",
            "Patience: Recognizing that true healing takes time.",
            "Blending: Merging diverse elements into a cohesive whole.",
            "Healing: Restoring equilibrium within body and mind.",
            "Caution: Moving forward with measured, thoughtful steps.",
            "Adaptability: Adjusting to change while maintaining balance.",
            "Synergy: Combining energies for a more potent effect.",
            "Equilibrium: Finding stability amid fluctuating circumstances.",
            "Fusion: Uniting contrasting ideas to form a better vision.",
            "Integration: Harmonizing disparate elements into a unified path.",
            "Self‑Control: Exercising restraint for long‑term benefit.",
            "Recovery: Gradually regaining strength and composure.",
            "Serenity: Embracing peace through balanced living."
        )
        "The Devil" -> listOf(
            "Temptation: Confronting the allure of excess and indulgence.",
            "Bondage: Recognizing self‑imposed limitations and breaking free.",
            "Materialism: Examining attachments to worldly possessions.",
            "Addiction: Facing behaviors that hinder your growth.",
            "Shadow: Acknowledging and integrating your darker aspects.",
            "Illusion: Seeing past deceptive appearances to the truth within.",
            "Control: Identifying areas where you feel trapped by habits.",
            "Obsession: Understanding the grip of compulsive behavior.",
            "Entanglement: Realizing the cost of unhealthy dependencies.",
            "Self‑Awareness: Recognizing patterns that restrict your freedom.",
            "Inner Demons: Confronting fears that undermine your progress.",
            "Restriction: Noticing how limiting beliefs impede success.",
            "Temptation: Weighing the benefits and drawbacks of indulgence.",
            "Liberation: Striving to reclaim your personal power.",
            "Transformation: Using insight to break free from destructive cycles."
        )
        "The Tower" -> listOf(
            "Disruption: Experiencing a sudden shake‑up in established norms.",
            "Revelation: Uncovering hidden truths amid chaos.",
            "Crisis: Recognizing that breakdowns can lead to breakthroughs.",
            "Shock: Accepting that dramatic change is sometimes necessary.",
            "Transformation: Allowing upheaval to clear the path for renewal.",
            "Release: Letting go of old structures that no longer serve you.",
            "Awakening: Realizing that crisis can spark profound insight.",
            "Destruction: Understanding that the fall of old ways makes room for growth.",
            "Insight: Gaining clarity from the ruins of what once was.",
            "Breakdown: Recognizing that collapse can be a precursor to rebuilding.",
            "Reconstruction: Seeing potential in starting over from scratch.",
            "Uncertainty: Accepting instability as part of evolution.",
            "Revelation: Discovering truth through the dismantling of falsehoods.",
            "Liberation: Breaking free from outdated systems.",
            "Renewal: Embracing the promise of a new beginning after chaos."
        )
        "The Star" -> listOf(
            "Hope: Embracing a renewed sense of optimism for the future.",
            "Inspiration: Drawing creative energy from the cosmos.",
            "Healing: Allowing time for recovery both physically and emotionally.",
            "Guidance: Trusting in the subtle messages from the universe.",
            "Serenity: Finding calm amid life’s turbulence.",
            "Faith: Believing in the promise of a brighter tomorrow.",
            "Renewal: Experiencing rebirth after challenging times.",
            "Clarity: Gaining insight through quiet contemplation.",
            "Gratitude: Recognizing and appreciating life’s blessings.",
            "Calm: Cultivating inner peace despite external storms.",
            "Balance: Integrating hope with practical action.",
            "Inspiration: Letting creative visions lead your path.",
            "Optimism: Maintaining positivity as a guiding force.",
            "Vision: Envisioning a future filled with promise and light.",
            "Transformation: Evolving through the gentle power of hope."
        )
        "The Moon" -> listOf(
            "Illusion: Recognizing that appearances may be deceiving.",
            "Intuition: Trusting your gut when things seem unclear.",
            "Mystery: Embracing the enigmatic and unpredictable.",
            "Fear: Confronting hidden anxieties that cloud judgment.",
            "Subconscious: Exploring the depths of your inner world.",
            "Uncertainty: Navigating through ambiguity with care.",
            "Reflection: Delving into the layers beneath the surface.",
            "Deception: Being mindful of things that are not as they seem.",
            "Vulnerability: Allowing yourself to feel and understand hidden emotions.",
            "Transformation: Finding growth in the midst of confusion.",
            "Imagination: Tapping into creative insights from dreams.",
            "Shadow: Acknowledging parts of yourself you may have repressed.",
            "Mysticism: Exploring the spiritual dimensions of uncertainty.",
            "Cycles: Recognizing recurring patterns in your life.",
            "Revelation: Discovering clarity amid the obscurity."
        )
        "The Sun" -> listOf(
            "Vitality: Embracing energy, joy, and the warmth of success.",
            "Optimism: Radiating positivity and a zest for life.",
            "Clarity: Gaining a clear vision of your path forward.",
            "Enlightenment: Experiencing a burst of spiritual insight.",
            "Success: Celebrating achievements with confidence and grace.",
            "Happiness: Enjoying life’s simple pleasures and abundant joy.",
            "Innocence: Reconnecting with childlike wonder and simplicity.",
            "Growth: Flourishing through renewed self‑belief and energy.",
            "Confidence: Shining with self‑assuredness and positivity.",
            "Creativity: Expressing yourself freely and with passion.",
            "Prosperity: Attracting abundance in all areas of life.",
            "Energy: Harnessing dynamic forces for positive change.",
            "Positivity: Spreading light and warmth to those around you.",
            "Fulfillment: Finding deep satisfaction in your personal journey.",
            "Radiance: Illuminating your world with genuine, vibrant energy."
        )
        "Judgment" -> listOf(
            "Rebirth: Embracing a profound new chapter in your life.",
            "Evaluation: Reflecting on past actions to forge a better future.",
            "Awakening: Responding to an inner call for transformation.",
            "Redemption: Finding forgiveness and releasing past burdens.",
            "Renewal: Emerging stronger after introspection.",
            "Accountability: Accepting responsibility for your choices.",
            "Resurrection: Rising anew with clarity and purpose.",
            "Judgment: Making decisions with fairness and self‑awareness.",
            "Transformation: Letting go of old patterns in favor of growth.",
            "Insight: Gaining clarity through honest self‑reflection.",
            "Revelation: Discovering truths that guide your next steps.",
            "Awareness: Recognizing your inner voice as a guide.",
            "Forgiveness: Releasing guilt to move forward freely.",
            "Salvation: Embracing the opportunity to start over with wisdom.",
            "Clarity: Seeing your path ahead with renewed vision."
        )
        "The World" -> listOf(
            "Completion: Celebrating the end of a significant journey.",
            "Accomplishment: Recognizing the fruits of your hard work.",
            "Fulfillment: Feeling whole and integrated from within.",
            "Integration: Uniting diverse aspects of your life into harmony.",
            "Celebration: Embracing joy as you mark a major milestone.",
            "Harmony: Experiencing balance between inner and outer worlds.",
            "Unity: Recognizing the interconnectedness of all experiences.",
            "Wholeness: Acknowledging that you are complete as you are.",
            "Achievement: Honoring your successes and lessons learned.",
            "Satisfaction: Enjoying the rewards of personal growth.",
            "Journey: Reflecting on the path that brought you here.",
            "Evolution: Appreciating continuous transformation and progress.",
            "Balance: Integrating experiences into a cohesive whole.",
            "New Beginnings: Preparing for the next chapter in life.",
            "Transcendence: Rising above limitations to embrace your full potential."
        )
        else -> List(15) { index ->
            "Detail ${index + 1} for ${card.description}: No specific interpretation available."
        }
    }
}

fun getCardDetailsThai(card: TarotCard): List<String> {
    return when (card.description) {
        "The Fool" -> listOf(
            "การเริ่มต้นใหม่: ยอมรับการเริ่มต้นการเดินทางด้วยความมองโลกในแง่ดี",
            "ความไร้เดียงสา: เข้าหาชีวิตด้วยมุมมองที่สดใสและเบาใจ",
            "การผจญภัย: เปิดรับโอกาสที่ไม่คาดคิดในชีวิต",
            "เสรีภาพ: ปล่อยวางขนบธรรมเนียมและก้าวเข้าสู่ความเสี่ยง",
            "ความมองโลกในแง่ดี: เชื่อในอนาคตที่สดใส",
            "ศักยภาพ: ตระหนักถึงความเป็นไปได้ที่ไม่มีที่สิ้นสุด",
            "ความบริสุทธิ์: รักษาความสมดุลระหว่างความเสี่ยงและความตระหนัก",
            "การผจญภัย: สำรวจเส้นทางใหม่ด้วยความกระตือรือร้น",
            "ความคิดสร้างสรรค์: ใช้จินตนาการสร้างเส้นทางใหม่",
            "ความอยากรู้: รักษาความอยากรู้อยากเห็นแบบเด็ก",
            "ความเชื่อมั่น: เชื่อว่าจักรวาลสนับสนุนการเดินทางของคุณ",
            "การปลดปล่อย: ก้าวข้ามข้อจำกัดในอดีต",
            "การเริ่มต้นใหม่: เริ่มต้นด้วยพลังและความหวัง",
            "การสำรวจ: ค้นพบด้านใหม่ในตัวคุณเอง",
            "การเสี่ยง: ยอมรับความไม่แน่นอนเพื่อการเติบโต"
        )
        "The Magician" -> listOf(
            "การสร้างสรรค์: เปลี่ยนความคิดให้เป็นจริงด้วยจุดมุ่งหมายที่ชัดเจน",
            "ความชาญฉลาด: ใช้เครื่องมือและทักษะที่มีเพื่อเอาชนะอุปสรรค",
            "พลังใจ: ควบคุมพลังภายในเพื่อสร้างความเปลี่ยนแปลง",
            "การลงมือทำ: ก้าวสู่เป้าหมายด้วยความมั่นใจ",
            "ความคิดสร้างสรรค์: ผสมผสานแรงบันดาลใจกับทักษะเพื่อสร้างสรรค์",
            "การมีสมาธิ: ใช้พลังงานให้เกิดผลลัพธ์ที่เป็นรูปธรรม",
            "ความมั่นใจ: เชื่อในความสามารถของตนเอง",
            "ความชำนาญ: พัฒนาทักษะผ่านการฝึกฝนอย่างต่อเนื่อง",
            "แรงบันดาลใจ: รับแรงบันดาลใจจากจักรวาล",
            "การริเริ่ม: คว้าโอกาสด้วยความมุ่งมั่น",
            "การสื่อสาร: แสดงออกอย่างชัดเจนเพื่อให้เห็นวิสัยทัศน์",
            "การเปลี่ยนแปลง: เปลี่ยนศักยภาพให้เป็นความจริง",
            "การเสริมพลัง: ตระหนักถึงพลังภายในของตนเอง",
            "การเป็นผู้นำ: นำทางผู้อื่นด้วยความมั่นใจ",
            "ความมุ่งมั่น: ยืนหยัดจนกว่าความฝันจะเป็นจริง"
        )
        "The High Priestess" -> listOf(
            "สัญชาตญาณ: เชื่อฟังเสียงภายในและสัญญาณจากจิตใต้สำนึก",
            "ความลึกลับ: เปิดรับความไม่รู้เพื่อค้นพบปัญญาที่ซ่อนเร้น",
            "ปัญญา: แสวงหาความรู้ลึกซึ้งเหนือสิ่งที่เห็น",
            "ความลับ: รู้ว่าบางความจริงค่อยๆ เผยออกมา",
            "จิตวิญญาณ: เชื่อมต่อกับตัวตนภายในและจิตสำนึกที่สูงส่ง",
            "การรับรู้: เข้าใจสัญญาณที่ละเอียดอ่อนในสิ่งแวดล้อม",
            "ความสงบ: พบความสันติในช่วงเวลาของการไตร่ตรอง",
            "การเข้าใจ: สำรวจสิ่งที่อยู่ลึกเพื่อหาความจริง",
            "สมดุล: ผสมผสานแสงและเงาในตัวคุณ",
            "การไตร่ตรอง: ให้เวลาสำหรับคิดค้นความหมายในชีวิต",
            "ความลึก: ค้นหาแง่มุมที่ซ่อนอยู่ในจิตใจ",
            "การตรองคิด: วิเคราะห์ความรู้สึกเพื่อให้ได้ความชัดเจน",
            "ความลึกลับ: ยอมรับความลึกลับในชีวิต",
            "ความอ่อนไหว: เปิดรับความละเอียดอ่อนของอารมณ์",
            "ความอดทน: ให้เวลาความจริงค่อยๆ ปรากฏตัว"
        )
        "The Empress" -> listOf(
            "ความอุดมสมบูรณ์: เฉลิมฉลองการเติบโตและผลตอบแทนจากการดูแล",
            "การดูแล: มอบความอบอุ่นและความรักให้แก่ตัวเองและผู้อื่น",
            "ความคิดสร้างสรรค์: สร้างแรงบันดาลใจและความงดงาม",
            "ความรู้สึก: เพลิดเพลินกับความสุขและความงามตามธรรมชาติ",
            "ความอุดมสมบูรณ์: สัญลักษณ์ของการสร้างสรรค์และการเริ่มต้นใหม่",
            "ความสะดวกสบาย: สร้างบรรยากาศที่เต็มไปด้วยความรัก",
            "ธรรมชาติ: เชื่อมต่อกับธรรมชาติเพื่อการรักษา",
            "ความรุ่งเรือง: เปิดรับชีวิตที่อุดมสมบูรณ์",
            "ความกลมกลืน: ค้นหาความสมดุลระหว่างความสัมพันธ์และความต้องการส่วนตัว",
            "ความงาม: ชื่นชมและสร้างความงามในทุกด้าน",
            "ความเห็นอกเห็นใจ: มอบความเมตตาและความเข้าใจ",
            "การเติบโต: ส่งเสริมการพัฒนาตัวเองและการเปลี่ยนแปลง",
            "การบำรุง: เติมเต็มทั้งร่างกายและจิตใจ",
            "พลังหญิง: เฉลิมฉลองความคิดสร้างสรรค์และสัญชาตญาณ",
            "ความมั่นคง: สร้างฐานที่มั่นคงสำหรับอนาคตที่สดใส"
        )
        "The Emperor" -> listOf(
            "อำนาจ: ยอมรับบทบาทผู้นำและสร้างโครงสร้างที่ชัดเจน",
            "การควบคุม: รับผิดชอบและควบคุมสถานการณ์ด้วยความมั่นใจ",
            "ความมั่นคง: สร้างรากฐานที่แข็งแกร่งสำหรับความสำเร็จ",
            "วินัย: รักษาระเบียบและความเป็นระเบียบในชีวิต",
            "ความรับผิดชอบ: ปฏิบัติตามหน้าที่ด้วยความจริงจัง",
            "โครงสร้าง: สร้างระบบที่ช่วยให้มองเห็นทางออกได้ชัดเจน",
            "พลัง: ใช้ความแข็งแกร่งภายในเพื่อควบคุมผลลัพธ์",
            "ความมั่นใจ: ยืนหยัดในความเชื่อและการตัดสินใจของตนเอง",
            "ตรรกะ: เผชิญกับความท้าทายด้วยความคิดที่เป็นระบบ",
            "การป้องกัน: รักษาสิ่งที่สำคัญในชีวิตของคุณ",
            "ความมุ่งมั่น: ก้าวต่อไปอย่างไม่หวั่นไหวแม้ในอุปสรรค",
            "ระเบียบ: พบความสงบในสภาพแวดล้อมที่เป็นระเบียบ",
            "ขอบเขต: ตระหนักและตั้งขอบเขตในชีวิตอย่างชัดเจน",
            "ประเพณี: เคารพวิธีการที่พิสูจน์มาแล้วจากอดีต",
            "มรดก: สร้างผลกระทบที่ยั่งยืนด้วยการนำที่ชาญฉลาด"
        )
        "The Hierophant" -> listOf(
            "ประเพณี: ยอมรับขนบธรรมเนียมและปัญญาที่สืบทอดมา",
            "การแนะแนวจิตวิญญาณ: ค้นหาคำแนะนำจากผู้ทรงคุณวุฒิ",
            "ความสอดคล้อง: รู้คุณค่าของการปฏิบัติตามวิธีที่ผ่านการทดสอบ",
            "ศรัทธา: ดึงพลังจากความเชื่อและค่านิยม",
            "การศึกษา: เรียนรู้ผ่านระบบและผู้ให้คำปรึกษาที่มีประสบการณ์",
            "จริยธรรม: ยึดมั่นในหลักการที่ถูกต้องในการตัดสินใจ",
            "ชุมชน: ให้ความสำคัญกับปัญญาร่วมและประสบการณ์ที่แบ่งปัน",
            "พิธีกรรม: มีส่วนร่วมในพิธีที่สรรเสริญประเพณี",
            "อนุรักษ์: เคารพในความรู้และประสบการณ์ของอดีต",
            "วินัย: ปฏิบัติตามเส้นทางที่มีโครงสร้างเพื่อความเข้าใจลึกซึ้ง",
            "การเชื่อมต่อจิตวิญญาณ: เสริมสร้างความสัมพันธ์กับสิ่งศักดิ์สิทธิ์",
            "การแนะแนว: เปิดรับคำแนะนำจากผู้มีประสบการณ์",
            "ความเป็นระเบียบ: พบความสบายในระบบที่จัดเรียงอย่างลงตัว",
            "พิธี: เฉลิมฉลองสิ่งศักดิ์สิทธิ์ผ่านพิธีกรรม",
            "การมีส่วนร่วม: ค้นหาที่ของคุณในชุมชนอันกว้างใหญ่"
        )
        "The Lovers" -> listOf(
            "ความสัมพันธ์: เฉลิมฉลองการเชื่อมต่ออันลึกซึ้งระหว่างจิตใจสองดวง",
            "ความกลมกลืน: หาจุดร่วมระหว่างความแตกต่างเพื่อสร้างความสมานฉันท์",
            "แรงดึงดูด: สัมผัสความดึงดูดที่เข้มข้นระหว่างผู้คน",
            "ความรัก: เปิดรับความโรแมนติกและความใกล้ชิดทางอารมณ์",
            "การเลือก: เผชิญกับการตัดสินใจสำคัญในความสัมพันธ์",
            "ความสอดคล้อง: หาความลงตัวในคุณค่าและความปรารถนา",
            "ความใกล้ชิด: เปิดเผยตัวตนและความเปราะบาง",
            "การผูกมัด: สร้างความสัมพันธ์ที่มั่นคงด้วยความไว้วางใจ",
            "ความหลงใหล: สัมผัสความรู้สึกที่ทรงพลังทั้งในใจและกาย",
            "การเชื่อมต่อ: ตระหนักถึงการเชื่อมโยงในระดับจิตวิญญาณ",
            "ความสมดุล: ผสานความแตกต่างให้กลมกลืนกัน",
            "การสื่อสาร: พูดคุยอย่างเปิดเผยเพื่อบำรุงความสัมพันธ์",
            "ความเปราะบาง: เปิดใจให้ผู้อื่นเข้าใจตัวตนที่แท้จริง",
            "การเป็นหุ้นส่วน: ร่วมมือกันเพื่อการเติบโตของทั้งคู่",
            "การรวมกัน: ผสานพลังของสองหัวใจให้เป็นหนึ่งเดียว"
        )
        "The Chariot" -> listOf(
            "ความมุ่งมั่น: ก้าวไปข้างหน้าด้วยความตั้งใจที่แน่วแน่",
            "ชัยชนะ: เอาชนะอุปสรรคด้วยพลังแห่งความมุ่งมั่น",
            "การควบคุม: รวมพลังตรงกันข้ามเพื่อขับเคลื่อนตัวเอง",
            "จังหวะ: สร้างพลังและความมุ่งหมายผ่านการลงมือทำ",
            "วินัย: ยึดมั่นในเส้นทางแม้ในยามที่มีสิ่งรบกวน",
            "ความทะเยอทะยาน: มุ่งสู่เป้าหมายอย่างชัดเจน",
            "ความมั่นใจ: เชื่อในความสามารถของตนเองในการพิชิตอุปสรรค",
            "ความสมดุล: ผสานพลังตรงกันข้ามให้เกิดความกลมกลืน",
            "การเดินทาง: เริ่มต้นการเดินทางทั้งภายในและภายนอก",
            "พลังใจ: แสดงพลังในการเอาชนะความยากลำบาก",
            "ชัยชนะ: เฉลิมฉลองความสำเร็จที่มาจากความพยายาม",
            "ความมุ่งมั่น: เดินหน้าตามเป้าหมายที่ตั้งไว้",
            "ความกล้าหาญ: เผชิญกับอุปสรรคด้วยใจที่ไม่หวาดกลัว",
            "ความยืดหยุ่น: ยืนหยัดแม้ในเวลาที่ท้าทาย",
            "การกำหนดทิศทาง: นำทางชีวิตด้วยความชัดเจน"
        )
        "Strength" -> listOf(
            "ความกล้าหาญ: ค้นพบความกล้าภายในเพื่อเผชิญหน้ากับอุปสรรค",
            "ความเห็นอกเห็นใจ: ใช้ความเมตตาเพื่อเอาชนะความท้าทาย",
            "ความมุ่งมั่น: ยืนหยัดด้วยความเงียบสงบแม้ในยามลำบาก",
            "ความอดทน: ผ่านพ้นอุปสรรคด้วยความสงบและอดทน",
            "ความยืดหยุ่น: ฟื้นตัวจากความล้มเหลวด้วยพลังใจที่เข้มแข็ง",
            "พลังภายใน: ตระหนักถึงความแข็งแกร่งที่ซ่อนอยู่ในตัวคุณ",
            "การควบคุมตนเอง: ฝึกควบคุมอารมณ์ด้วยความอ่อนโยน",
            "ความเมตตา: ใช้ความเห็นอกเห็นใจเป็นแหล่งพลังที่แท้จริง",
            "พลังใจ: รู้จักความเข้มแข็งในใจของคุณ",
            "ความพากเพียร: ยืนหยัดในความเชื่อแม้เผชิญความยากลำบาก",
            "ความสง่างาม: เผชิญอุปสรรคด้วยความมีศักดิ์ศรี",
            "แรงบันดาลใจ: ใช้ความรู้สึกที่แรงกล้าเป็นแรงผลักดัน",
            "ความสมดุล: ผสานความเด็ดขาดกับความอ่อนโยน",
            "ความพยายาม: สู้ต่อไปแม้ในยามเหน็ดเหนื่อย",
            "ความมั่นใจ: เชื่อในความสามารถของตนเองในการเอาชนะอุปสรรค"
        )
        "The Hermit" -> listOf(
            "การไตร่ตรอง: แสวงหาปัญญาผ่านการสะท้อนตัวเอง",
            "การพินิจพิเคราะห์: ให้เวลาสำหรับการไตร่ตรองลึกซึ้ง",
            "ความรู้: เรียนรู้จากประสบการณ์และความเงียบสงบ",
            "การถอยหลัง: ห่างจากความวุ่นวายเพื่อค้นพบความชัดเจน",
            "การอยู่คนเดียว: ยอมรับช่วงเวลาของการอยู่คนเดียวเพื่อเข้าใจตัวเอง",
            "การแนะแนว: ฟังเสียงภายในเพื่อหาทิศทาง",
            "การทำสมาธิ: หาเวลาสงบในช่วงของการไตร่ตรอง",
            "การสะท้อน: เรียนรู้จากอดีตเพื่อสร้างอนาคต",
            "การค้นหาความจริง: สืบค้นหาปัญญาที่ซ่อนเร้น",
            "ความโดดเดี่ยว: ค้นพบคุณค่าของการอยู่คนเดียว",
            "การตรอง: ให้เวลาคิดเพื่อค้นหาความหมาย",
            "แสงสว่าง: พบแสงในความมืด",
            "การพึ่งพาตนเอง: เรียนรู้ที่จะพึ่งพาแรงใจในตัวเอง",
            "การอยู่สงบ: ยอมรับความเงียบเพื่อความชัดเจน",
            "การไตร่ตรองลึกซึ้ง: ค้นพบความหมายในช่วงเวลาของความเงียบ"
        )
        "Wheel of Fortune" -> listOf(
            "วัฏจักร: ตระหนักถึงการเปลี่ยนแปลงและการหมุนเวียนในชีวิต",
            "ชะตากรรม: รับรู้ว่าชะตากรรมมีส่วนในเส้นทางชีวิต",
            "การเปลี่ยนแปลง: เปิดรับความไม่แน่นอนที่เกิดขึ้นตลอดเวลา",
            "กรรม: เข้าใจว่าทุกการกระทำมีผลตามมา",
            "โอกาส: คว้าโอกาสเมื่อมันมาถึงโดยไม่คาดคิด",
            "ความบังเอิญ: ยอมรับว่าความโชคดีสามารถเปลี่ยนแปลงได้",
            "ชะตากรรม: ตระหนักว่าบางสิ่งอยู่นอกเหนือการควบคุม",
            "เหตุการณ์พลิกผัน: สังเกตการเปลี่ยนแปลงที่เกิดขึ้นทันที",
            "การไหลเวียน: ปรับตัวเข้ากับการเปลี่ยนแปลงอย่างคล่องตัว",
            "ความลึกลับ: รับรู้สิ่งที่ยังไม่เปิดเผย",
            "ความโชคดี: เปิดรับทั้งด้านดีและร้ายในชีวิต",
            "การสิ้นสุดของวงจร: สังเกตจุดจบและจุดเริ่มต้นใหม่",
            "แรงขับเคลื่อน: ใช้การเปลี่ยนแปลงเป็นแรงผลักดัน",
            "การเปลี่ยนแปลงที่ไม่คาดคิด: เปิดใจรับสิ่งที่ไม่คาดฝัน",
            "ความนิรันดร์: ตระหนักว่าการหมุนเวียนของชีวิตไม่มีที่สิ้นสุด"
        )
        "Justice" -> listOf(
            "ความยุติธรรม: มุ่งมั่นสร้างความสมดุลและความเป็นธรรม",
            "ความจริง: เผชิญหน้ากับความเป็นจริงอย่างตรงไปตรงมา",
            "ความรับผิดชอบ: ตระหนักว่าการกระทำมีผลตามมา",
            "ความซื่อสัตย์: ยึดมั่นในหลักจริยธรรมในการตัดสินใจ",
            "กฎเกณฑ์: เคารพในระเบียบและโครงสร้างของสังคม",
            "ความสมดุล: ชั่งน้ำหนักทุกฝ่ายอย่างเป็นธรรม",
            "การรับผิดชอบ: ยอมรับผลของการกระทำตนเอง",
            "ความชัดเจน: แสวงหาความโปร่งใสในสถานการณ์",
            "ความเท่าเทียม: มุ่งมั่นปฏิบัติต่อทุกฝ่ายอย่างเท่าเทียม",
            "เหตุผล: ใช้ตรรกะในการแก้ไขข้อพิพาท",
            "การตัดสิน: ประเมินสถานการณ์ด้วยความเป็นธรรม",
            "ความเป็นกลาง: ลบความเอนเอียงเพื่อเห็นความจริง",
            "การประนีประนอม: คืนความสมดุลหลังความขัดแย้ง",
            "การตัดสินใจ: เลือกทางด้วยจิตใจที่เปิดกว้าง",
            "กรรม: ตระหนักว่าความยุติธรรมจะคืนกลับมาในที่สุด"
        )
        "The Hanged Man" -> listOf(
            "การยอมแพ้: ปล่อยวางการควบคุมเพื่อเปิดรับมุมมองใหม่",
            "การหยุดนิ่ง: ยอมรับความจำเป็นของการหยุดเพื่อไตร่ตรอง",
            "การสละสลวย: เข้าใจว่าการปล่อยวางนำไปสู่การเติบโต",
            "มุมมองใหม่: มองปัญหาจากด้านที่ต่างออกไป",
            "การปล่อยวาง: ปล่อยวางรูปแบบเดิมเพื่อเปิดรับการเปลี่ยนแปลง",
            "การยอมรับ: เปิดรับความไม่แน่นอนแม้ในเวลาที่รู้สึกไม่สบาย",
            "ความอดทน: เชื่อว่าความจริงจะปรากฏขึ้นตามเวลา",
            "การค้นพบ: หาปัญญาจากช่วงเวลาที่เงียบสงบ",
            "การพลิกผัน: ตระหนักว่ามุมมองใหม่สามารถเปลี่ยนความเข้าใจ",
            "การไตร่ตรอง: ให้เวลากับการคิดลึกซึ้งเพื่อค้นหาความหมาย",
            "การกลับด้าน: พบมุมมองที่เปลี่ยนแปลงความเข้าใจ",
            "การเปลี่ยนแปลง: ยอมรับว่าการเปลี่ยนแปลงเริ่มต้นจากการหยุดนิ่ง",
            "การสะท้อน: ใช้เวลาสำหรับการเรียนรู้จากความเงียบ",
            "การสละ: ตระหนักว่าการปล่อยวางสิ่งเก่าเปิดทางสู่สิ่งใหม่",
            "การเริ่มต้นใหม่: พบการเปลี่ยนแปลงในความเงียบและการพักผ่อน"
        )
        "Death" -> listOf(
            "การเปลี่ยนแปลง: ยอมรับการสิ้นสุดของช่วงหนึ่งเพื่อเปิดรับสิ่งใหม่",
            "การปล่อยวาง: ปล่อยวางสิ่งเก่าเพื่อให้เกิดการเติบโตใหม่",
            "การเปลี่ยนผ่าน: รู้ว่าการสิ้นสุดเป็นทางเข้าสู่การเริ่มต้นใหม่",
            "การเกิดใหม่: ทุกการสิ้นสุดเป็นโอกาสในการเกิดใหม่",
            "การปิดฉาก: รับรู้ว่าการจบสิ้นเป็นส่วนหนึ่งของวัฏจักรชีวิต",
            "การทำความสะอาด: ปล่อยวางสิ่งที่ไม่จำเป็นเพื่อพัฒนา",
            "การปล่อยวาง: ให้โอกาสตัวเองก้าวผ่านอดีต",
            "การเปลี่ยนรูป: เปลี่ยนแปลงเพื่อความก้าวหน้า",
            "การเปลี่ยนแปลงลึกซึ้ง: เติบโตผ่านการผ่านพ้นสิ่งเก่า",
            "การยอมรับ: ยอมรับความจริงของการเปลี่ยนแปลง",
            "การวิวัฒนาการ: เรียนรู้จากการสิ้นสุดเพื่อก้าวต่อไป",
            "การปรับตัว: เปลี่ยนแปลงและปรับตัวให้เข้ากับสถานการณ์ใหม่",
            "การสร้างใหม่: เปิดรับการเปลี่ยนแปลงเพื่ออนาคตที่สดใส",
            "ความยืดหยุ่น: ฟื้นตัวจากการสิ้นสุดด้วยความแข็งแกร่ง",
            "ขอบฟ้าใหม่: มองหาความหวังในจุดเริ่มต้นใหม่"
        )
        "Temperance" -> listOf(
            "ความสมดุล: ผสานพลังตรงกันข้ามเพื่อสร้างความกลมกลืน",
            "ความพอประมาณ: หลีกเลี่ยงความสุดโต่งในความคิดและการกระทำ",
            "ความหมาย: รวมเอาส่วนต่างๆในชีวิตเข้าด้วยกัน",
            "ความอดทน: รู้ว่าการรักษาสมดุลต้องใช้เวลา",
            "การผสมผสาน: รวมองค์ประกอบที่หลากหลายให้เป็นหนึ่งเดียว",
            "การรักษา: คืนความสมดุลให้กับร่างกายและจิตใจ",
            "ความระมัดระวัง: ก้าวไปข้างหน้าด้วยความคิดอย่างรอบคอบ",
            "ความยืดหยุ่น: ปรับตัวเข้ากับการเปลี่ยนแปลงโดยไม่สูญเสียความสมดุล",
            "พลังร่วม: ผสมพลังเพื่อให้เกิดผลลัพธ์ที่ดีขึ้น",
            "ความเท่าเทียม: ค้นหาความเสมอภาคในทุกด้าน",
            "การรวมกัน: ผสานองค์ประกอบต่างๆให้กลมกลืน",
            "การบูรณาการ: รวมทุกอย่างเข้าด้วยกันในเส้นทางเดียว",
            "การควบคุมตนเอง: ใช้ความระมัดระวังเพื่อประโยชน์ในระยะยาว",
            "การฟื้นฟู: ค่อยๆ กลับมามีพลังอีกครั้งหลังจากความลำบาก",
            "ความสงบ: ค้นหาความเงียบสงบผ่านการมีสมดุลในชีวิต"
        )
        "The Devil" -> listOf(
            "การล่อลวง: เผชิญหน้ากับความเย้ายวนของความเกินและการหลงใหล",
            "การถูกผูกมัด: รับรู้ข้อจำกัดที่ตัวเองสร้างขึ้นและต้องการการปลดปล่อย",
            "ความวัตถุนิยม: ตรวจสอบความผูกพันกับสิ่งของในโลกนี้",
            "การติดยึด: เผชิญกับพฤติกรรมที่ขัดขวางการเติบโต",
            "เงามืด: รับรู้และยอมรับด้านมืดในตัวเอง",
            "ภาพลวงตา: มองผ่านความลวงเพื่อค้นหาความจริง",
            "การควบคุม: สังเกตพื้นที่ที่คุณรู้สึกติดอยู่กับนิสัยเก่า",
            "การหมกมุ่น: ตระหนักถึงผลของการหมกมุ่นที่ขัดขวางความก้าวหน้า",
            "การพันธนาการ: เห็นความเสียหายจากการพึ่งพาสิ่งที่ไม่ดี",
            "การรู้จักตัวเอง: เรียนรู้จากนิสัยที่ขัดขวางความเจริญ",
            "ปีศาจภายใน: เผชิญหน้ากับความกลัวที่ขัดขวางความสำเร็จ",
            "ข้อจำกัด: มองเห็นขีดจำกัดที่เกิดจากความเชื่อในอดีต",
            "การล่อลวง: ประเมินผลประโยชน์และความเสี่ยงของการหลงใหล",
            "การปลดปล่อย: มุ่งมั่นที่จะกลับคืนสู่ความเป็นตัวเอง",
            "การเปลี่ยนแปลง: ใช้ความเข้าใจเพื่อก้าวผ่านวัฏจักรเดิม"
        )
        "The Tower" -> listOf(
            "ความไม่มั่นคง: เผชิญกับการสั่นคลอนในระบบที่คุ้นเคย",
            "การเปิดเผย: เปิดรับความจริงที่ซ่อนอยู่ในความวุ่นวาย",
            "วิกฤติ: รับรู้ว่าการแตกสลายนำไปสู่การเปลี่ยนแปลงที่สำคัญ",
            "ความช็อก: ยอมรับว่าความเปลี่ยนแปลงต้องมาพร้อมความสั่นสะเทือน",
            "การเปลี่ยนแปลง: ปล่อยให้ความล้มเหลวเป็นจุดเริ่มต้นใหม่",
            "การปลดปล่อย: ปลดปล่อยสิ่งเก่าเพื่อเปิดทางสู่สิ่งใหม่",
            "การตื่นรู้: ตระหนักว่าความวุ่นวายอาจนำมาซึ่งปัญญา",
            "การทำลาย: เข้าใจว่าการล่มสลายเปิดโอกาสให้เกิดสิ่งใหม่",
            "การค้นพบ: ค้นหาความหมายในความวุ่นวาย",
            "การล่มสลาย: รับรู้ว่าการแตกสลายเป็นส่วนหนึ่งของการเติบโต",
            "การสร้างใหม่: พบโอกาสในการเริ่มต้นใหม่จากความเสียหาย",
            "ความไม่แน่นอน: ยอมรับความไม่แน่นอนในชีวิต",
            "การเปิดตา: ค้นพบความจริงผ่านการล่มสลาย",
            "การหลุดพ้น: ปลดปล่อยจากระบบที่ล้าสมัย",
            "การฟื้นฟู: เฉลิมฉลองการเกิดใหม่หลังจากความวุ่นวาย"
        )
        "The Star" -> listOf(
            "ความหวัง: เปิดรับความหวังและมองเห็นอนาคตที่สดใส",
            "แรงบันดาลใจ: รับแรงบันดาลใจจากความงดงามของจักรวาล",
            "การรักษา: ให้เวลากับการฟื้นฟูทั้งร่างกายและจิตใจ",
            "การแนะแนว: เชื่อฟังสัญญาณจากจักรวาล",
            "ความสงบ: พบความสันติในช่วงเวลาที่เงียบสงบ",
            "ศรัทธา: ยึดมั่นในความเชื่อและความหวังในวันข้างหน้า",
            "การเกิดใหม่: ฟื้นฟูจิตใจหลังจากช่วงเวลาที่ยากลำบาก",
            "ความชัดเจน: ได้รับความเข้าใจจากความเงียบ",
            "ความกตัญญู: ชื่นชมสิ่งดีในชีวิต",
            "ความสงบ: รักษาความเย็นชาแม้ในวิกฤติ",
            "ความสมดุล: ผสานความหวังกับการลงมือทำ",
            "แรงบันดาลใจ: ให้จิตใจคุณเป็นแหล่งสร้างสรรค์",
            "ความมองโลกในแง่ดี: ยึดถือความคิดบวกในทุกสถานการณ์",
            "วิสัยทัศน์: มองเห็นอนาคตที่เต็มไปด้วยความหวัง",
            "การเปลี่ยนแปลง: ก้าวสู่การเปลี่ยนแปลงด้วยความหวังที่ยั่งยืน"
        )
        "The Moon" -> listOf(
            "ภาพลวงตา: ตระหนักว่าบางสิ่งอาจไม่เป็นอย่างที่เห็น",
            "สัญชาตญาณ: ฟังเสียงในใจเมื่อทุกอย่างคลุมเครือ",
            "ความลึกลับ: เปิดรับความไม่แน่นอนและความลึกลับ",
            "ความกลัว: เผชิญหน้ากับความกลัวที่ซ่อนอยู่ในจิตใต้สำนึก",
            "จิตใต้สำนึก: สำรวจความรู้สึกที่ซ่อนเร้นภายในใจ",
            "ความไม่แน่นอน: รับรู้ความคลุมเครือของสถานการณ์",
            "การสะท้อน: ค้นหาความหมายที่อยู่ใต้พื้นผิว",
            "การหลอกลวง: ระวังสิ่งที่อาจไม่เป็นความจริง",
            "ความเปราะบาง: เปิดรับความอ่อนแอและความจริงใจ",
            "การเปลี่ยนแปลง: เติบโตผ่านความสับสนในชีวิต",
            "จินตนาการ: ใช้จินตนาการเปิดโลกทัศน์ใหม่",
            "เงา: ยอมรับด้านมืดในตัวคุณ",
            "ความลึกลับ: ค้นพบความหมายในความไม่ชัดเจน",
            "วัฏจักร: สังเกตการเปลี่ยนแปลงที่เกิดซ้ำในชีวิต",
            "การเปิดเผย: ค้นพบความจริงในความมืดที่แฝงอยู่"
        )
        "The Sun" -> listOf(
            "พลังงาน: รับพลังแห่งความสุขและความสดใสในชีวิต",
            "ความมองโลกในแง่ดี: เปล่งประกายด้วยความคิดบวกและความสุข",
            "ความชัดเจน: มองเห็นเส้นทางที่ชัดเจนในชีวิต",
            "การตรัสรู้: สัมผัสความรู้แจ้งทางจิตวิญญาณ",
            "ความสำเร็จ: เฉลิมฉลองความสำเร็จด้วยความมั่นใจ",
            "ความสุข: เพลิดเพลินกับสิ่งเล็กๆ ที่นำความสุข",
            "ความไร้เดียงสา: กลับไปสู่ความบริสุทธิ์ในใจ",
            "การเติบโต: เติบโตไปพร้อมกับพลังและความสดใส",
            "ความมั่นใจ: ส่องสว่างด้วยความมั่นใจในตนเอง",
            "ความคิดสร้างสรรค์: แสดงออกด้วยความคิดริเริ่ม",
            "ความรุ่งเรือง: ดึงดูดความอุดมสมบูรณ์ในทุกด้าน",
            "พลังชีวิต: ใช้พลังเพื่อสร้างสิ่งดีๆ",
            "ความสุขใจ: พบความพึงพอใจในทุกการกระทำ",
            "ความอบอุ่น: แผ่ความรักและความอบอุ่นสู่ผู้อื่น",
            "การเปล่งประกาย: ส่องสว่างโลกด้วยความสุขแท้จริง"
        )
        "Judgment" -> listOf(
            "การเกิดใหม่: ต้อนรับบทใหม่ในชีวิตด้วยความมั่นใจ",
            "การประเมินผล: ทบทวนอดีตเพื่อสร้างอนาคตที่ดีกว่า",
            "การตื่นรู้: ตอบสนองต่อสัญญาณภายในเพื่อการเปลี่ยนแปลง",
            "การไถ่ถอน: ปล่อยวางความผิดในอดีตเพื่อเริ่มต้นใหม่",
            "การเกิดใหม่: เรียนรู้จากอดีตเพื่อสร้างอนาคต",
            "ความรับผิดชอบ: ยอมรับผลของการตัดสินใจตนเอง",
            "การฟื้นคืนชีพ: ฟื้นฟูจิตใจหลังผ่านช่วงเวลาที่ยากลำบาก",
            "การตัดสิน: ตัดสินใจด้วยความยุติธรรมและความรู้สึกจริงใจ",
            "การเปลี่ยนแปลง: ปล่อยให้การเปลี่ยนแปลงนำไปสู่การเติบโต",
            "การเข้าใจ: ค้นพบความจริงผ่านการไตร่ตรอง",
            "การเปิดเผย: เปิดรับคำตอบจากภายในจิตใจ",
            "การให้อภัย: ปล่อยวางความโกรธและความเจ็บปวดในอดีต",
            "การไถ่บาป: ยอมรับความผิดพลาดและก้าวต่อไป",
            "การรื้อฟื้น: ปลุกจิตใจให้มีความหวังใหม่",
            "ความชัดเจน: มองเห็นเส้นทางสู่อนาคตที่สดใส"
        )
        "The World" -> listOf(
            "ความสมบูรณ์: เฉลิมฉลองความสำเร็จของการเดินทางที่ยาวนาน",
            "การบรรลุ: รับรู้ผลลัพธ์จากความพยายามที่ต่อเนื่อง",
            "ความสมบูรณ์: รู้สึกถึงความเป็นหนึ่งและความสมบูรณ์ภายใน",
            "การรวมกัน: รวมเอาประสบการณ์ทั้งหมดให้เป็นหนึ่งเดียว",
            "การเฉลิมฉลอง: เฉลิมฉลองความสำเร็จในชีวิต",
            "ความกลมกลืน: พบความสมดุลระหว่างโลกภายในและภายนอก",
            "ความเป็นหนึ่ง: ตระหนักถึงการเชื่อมต่อของทุกสิ่งในจักรวาล",
            "ความครบถ้วน: รับรู้ว่าคุณเป็นส่วนหนึ่งของภาพใหญ่",
            "การบรรลุเป้าหมาย: เฉลิมฉลองชัยชนะที่มาจากความพยายาม",
            "ความพึงพอใจ: รู้สึกถึงความสำเร็จจากการเติบโตส่วนตัว",
            "การเดินทาง: ทบทวนเส้นทางที่นำคุณมาถึงที่นี่",
            "การวิวัฒนาการ: ตระหนักถึงการเปลี่ยนแปลงอย่างต่อเนื่อง",
            "ความสมดุล: ผสานประสบการณ์ให้เป็นหนึ่งเดียว",
            "การเริ่มต้นใหม่: เตรียมพร้อมสำหรับบทใหม่ในชีวิต",
            "การก้าวข้าม: ก้าวผ่านขีดจำกัดสู่ความเป็นอิสระและความยิ่งใหญ่"
        )
        else -> List(15) { index ->
            "รายละเอียด ${index + 1} สำหรับ ${card.description}: ไม่มีการตีความเฉพาะ"
        }
    }
}
